language: generic

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.local/bin/
    - .stack-work/

before_install:
  - scripts/travis_setup.sh

script:
  - travis_wait stack --no-terminal test
  - travis_wait stack --no-terminal haddock

branches:
  only:
    - master
