language: generic

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
  - os: osx

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/.local/bin/"
  - ".stack-work/"

before_install:
- scripts/travis_setup.sh

install:
- travis_wait 30 stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
- stack --local-bin-path . install groot
- mv groot "groot-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: groot-*
  skip_cleanup: true
  on:
    repo: alonsodomin/groot
    tags: true
