language: generic

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.local/bin/
    - .stack-work/

before_install:
  - scripts/travis_setup.sh

install:
  - travis_wait stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --only-snapshot --haddock --no-haddock-deps

branches:
  only:
    - master
