language: generic

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.local/bin/
    - .stack-work/

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ ! -x ~/.local/bin/stack ]]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
  - stack --version
  
  # Install GHC
  - stack setup
  - stack exec -- ghc --version

script:
  - stack --no-terminal test
  - stack --no-terminal haddock

branches:
  only:
    - master